name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v3
        - name: Configurar JDK 17 para x64
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'
            architecture: x64
        - name: Validar Gradle wrapper
          uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
        - name: Executar tarefa de teste do Gradle
          uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
          with:
            arguments: test
